#pragma once

inline const int MODE_FLAG_SEARCH = 0x1;
inline const int MODE_FLAG_REPLACE = 0x2;
inline const int MODE_FLAG_FILE = 0x4;
inline const int MODE_FLAG_DIRECTORY = 0x8;
inline const int MODE_FLAG_FILES = 0x10;

inline const int MODE_SEARCH = MODE_FLAG_SEARCH | MODE_FLAG_FILE;
inline const int MODE_REPLACE = MODE_FLAG_REPLACE | MODE_FLAG_FILE;
inline const int MODE_SEARCH_DIRECTORY = MODE_FLAG_SEARCH | MODE_FLAG_DIRECTORY;
inline const int MODE_REPLACE_DIRECTORY = MODE_FLAG_REPLACE | MODE_FLAG_DIRECTORY;
inline const int MODE_SEARCH_OPENED_FILES = MODE_FLAG_SEARCH | MODE_FLAG_FILES;
inline const int MODE_REPLACE_OPENED_FILES = MODE_FLAG_REPLACE | MODE_FLAG_FILES;
